version: '2'
services:
    application:
        build: .
        volumes:
            - .:/code
        environment:
            - QUEUE_HOST=
            - QUEUE_PORT=
            - QUEUE_USER=
            - QUEUE_PASSWORD=
            - SMTP_HOST=
            - SMTP_PORT=
            - SMTP_SECURITY=
            - SMTP_USERNAME=
            - SMTP_PASSWORD=